name: SHOP Website Secure CI/CD Pipeline

# Trigger the pipeline when code is pushed to the master branch on git
on:
  push:
    branches:
      - main
     
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for running the app
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # You can adjust this to any Node.js version

      # Step 3: Install the Node.js application dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint for static analysis (SAST)
      - name: Run ESLint (SAST)
        run: npx eslint .

      # Step 5: Run Snyk for dependency vulnerability scanning
      - name: Scan dependencies with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # You must add your Snyk token in the repository secrets

      # Step 6: Build Docker image for your app
      - name: Build Docker image
        run: docker build -t myappshop:latest .

      # Step 7: Scan Docker image with Trivy for vulnerabilities
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest

      # Step 8: Run the containerized application
      - name: Run Docker container
        run: docker run -d -p 3000:3000 myappshop:latest

      # Step 9: OWASP ZAP Scan (DAST)
      - name: Run OWASP ZAP (DAST)
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'  # This is the target app running in Docker
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-r report_html.html' # ZAP will generate the HTML report

          
      # Step 10: Upload ZAP report as an artifact for future reference
      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: report_html
          path: report_html.html
